*** Settings ***
Documentation    Ce fichier contient les variables globales du projet


*** Variables ***
${pathPDF-cours1}    TP2/exercices/resources/Cours1AutomatisationTestsBUT20232024.pdf
${pathPDF-cours2}    TP2/exercices/resources/Cours2AutomatisationTests20232024.pdf
${pathPDF-random}    TP2/exercices/resources/unPDFrandom.pdf

${pathDirectory-downloaded}    TP2/exercices/resources/downloaded/
${pathDirectory-accepted}    TP2/exercices/resources/candidatsAccepted/
${pathDirectory-refused}    TP2/exercices/resources/candidatsRefused/