*** Variables ***
${link-enter}         xpath=//*[@id="Content"]/p/a
${link-signIn}        xpath=//*[@id="MenuContent"]/a[2]
${link-register}      xpath=//*[@id="Catalog"]/a
${link-saveAccount}   //*[@name="newAccount"]
${link-signon}        //*[@name="signon"]

${link-fish}         xpath=//*[@id="QuickLinks"]/a[1]
${link-dogs}         xpath=//*[@id="QuickLinks"]/a[2]
${link-reptiles}     xpath=//*[@id="QuickLinks"]/a[3]
${link-cats}         xpath=//*[@id="QuickLinks"]/a[4]
${link-birds}        xpath=//*[@id="QuickLinks"]/a[5]
${link-home}         xpath=//*[@id="BackLink"]/a

${image-mainPage}     //*[@id="MainImageContent"]
