*** Variables ***
${link-enter}         xpath=//*[@id="Content"]/p/a
${link-signIn}        xpath=//*[@id="MenuContent"]/a[2]
${link-register}      xpath=//*[@id="Catalog"]/a
${link-saveAccount}   //*[@name="newAccount"]
${link-signon}        //*[@name="signon"]
${link-signout}       xpath=//*[@id="MenuContent"]/a[2]

${link-fish-top}         xpath=//*[@id="QuickLinks"]/a[1]
${link-fish-left}        xpath=//*[@id="SidebarContent"]/a[1]
${link-dogs-top}         xpath=//*[@id="QuickLinks"]/a[2]
${link-dogs-left}        xpath=//*[@id="SidebarContent"]/a[2]
${link-reptiles-top}     xpath=//*[@id="QuickLinks"]/a[3]
${link-reptiles-left}    xpath=//*[@id="SidebarContent"]/a[4]
${link-cats-top}         xpath=//*[@id="QuickLinks"]/a[4]
${link-cats-left}        xpath=//*[@id="SidebarContent"]/a[3]
${link-birds-top}        xpath=//*[@id="QuickLinks"]/a[5]
${link-birds-left}       xpath=//*[@id="SidebarContent"]/a[5]
${link-home}             xpath=//*[@id="BackLink"]/a

${image-mainPage}     //*[@id="MainImageContent"]
